### ISSUE TITLE
React UI Components

### ISSUE THREAD

**Issue by SachaG** [orionsoft/meteor-apollo-accounts#12]
This is a pretty awesome project for people using Meteor+Apollo, but what about the UI layer? Can this work with something like [accounts-ui](https://github.com/studiointeract/accounts-ui)? Or do you just roll out your own components?

**Comment by janikvonrotz** [comment]
For now you have roll out your own components. In order make it work with accounts-ui I think there are two ways to go:

1. Override the accounts methods such as `Meteor.loginWithPassword` and pass the params to the `loginWithPassword({ email, password }, ApolloClient)` method of this package.

2. Create a fork of accounts-ui and make it using the methods from this package.

@nicolaslopezj do you agree on that?

Here's and example of a custom component using this package: [Login.js](https://github.com/janikvonrotz/meteor-apollo-accounts-example/blob/master/client/Login.js)

**Comment by SachaG** [comment]
I think a fork might work better. Or maybe even add the React components to this package directly? Or do you want to keep it UI-free @nicolaslopezj?

**Comment by nicolaslopezj** [comment]
I want to keep it ui free, but we could make another ui package for this in React
