### ISSUE TITLE
Meteor is not aware of the session changes

### ISSUE THREAD

**Issue by zvictor** [orionsoft/meteor-apollo-accounts#43]
While trying to use `loginWithPassword` in a Meteor app, I realised that even though my user was logged in, Meteor was not aware of it (`Meteor.userId() === null`).

Checking the code I couldn't find any call to `Accounts.makeClientLoggedIn`, `Accounts.connection.setUserId` or similar. Shouldn't it be the case?

**Comment by dbrrt** [comment]
I think the aim of this library is to make use of Meteor accounts for user layer in the Backend for any kind of application as front-end, but as this is using standard accounts Meteor remote methods, it should notify that an account is authenticated Meteor side. The library is also intended to have users features without DDP.

**Comment by zvictor** [comment]
An application like mine, still highly dependent on DDP, would expect `loginWithPassword` to trigger the same callbacks as `Meteor.loginWithPassword`. Otherwise, the DDP server is not aware that the user on that connection has changed, and publications don't react to the change.

I suggest we create a callback to be called from `tokenDidChange`, responsible for that. So far, the code looks something like that:

```js
  onTokenChange(({ userId }) => {
    if (Accounts) {
      Accounts.connection.setUserId(userId); // it updates the frontend
    }
    // TODO: make a DDP call, updating the server
  });
```

I have no experience working directly with DDP, but I guess we need to make a dummy DDP request, in order to have credentials exchanged and the server updated. Would it be the way to go here? How to achieve that?

**Comment by dbrrt** [comment]
That's a nice point, but we'll still have the same issue at import step that we had for AsyncStorage in React Native. If Accounts is reachable globally and no specific import is needed that'd be a way to go but less abstract than the current implementation.

**Comment by zvictor** [comment]
I agree that we need to be careful with Meteor code being added to this library as we don't want our apps to become more dependent on it.

The callback I suggested could be an opt-in, executed in a similar way to how we do now with `initAccounts()`. There could be a `syncMeteor()` available for that, that would call `onTokenChange` for us.
This way we would minimize the chances of having a conflict with other environments.

The challenge remains on DDP. Once the callback is in place, what can be done to update the authentication on the DDP server?

**Comment by dbrrt** [comment]
I'll investigate on the support of DDP for this library

**Comment by zvictor** [comment]
so far the best I could get is calling `loginWithToken`.

```js
  onTokenChange(({ userId, token }) => {
    Meteor.loginWithToken(token, () => {
      // Update Redux store, call callbacks, whatever...
    });
  });
```

**Comment by dbrrt** [comment]
I think this's one way to solve your problem. Have you been able to got it working ?
This should be done directly in functions in your Meteor client as a callback of a Login call. Do you want an example that implements that approach ?
And sorry for the delay...

**Comment by zvictor** [comment]
Yes it works fine. I just hoped for a solution that was not dependent on Meteor-accounts.

**Comment by dbrrt** [comment]
That's a really good point, and I'm almost sure that Meteor accounts libraries are required to work on a Meteor Client, and should be installed both on Client and Server if they're both running Meteor.js and if you need you server communicating through DDP with the clients. I've tried to find a workaround to make it possible, but the one you proposed is nice too, especially if it's yet operational.

**Comment by nicolaslopezj** [comment]
The answer @zvictor posted is great, can you added to the docs?

This library tries to take out the Meteor in the client side, It should work without it
