### ISSUE TITLE
Error: Type "User" not found in document.

### ISSUE THREAD

**Issue by jschlieber** [orionsoft/meteor-apollo-accounts#44]
I get an `Error: Type "User" not found in document.` when trying to set up `apollo-accounts` as described in the README. Here is my code:
```js
import { createApolloServer } from 'meteor/apollo';
import { initAccounts } from 'meteor/nicolaslopezj:apollo-accounts';
import {
  makeExecutableSchema,
  addMockFunctionsToSchema,
} from 'graphql-tools';
import {
  loadSchema,
  getSchema,
} from 'graphql-loader';
import { typeDefs } from './schema';
import { resolvers } from './resolvers';

// Init Meteor apollo accounts
const options = {};
initAccounts(options);

// Load all resolvers and type definitions into graphql-loader
loadSchema({typeDefs, resolvers});

// Get all resolvers and type definitions loaded in graphql-loader
const schema = makeExecutableSchema(getSchema());

createApolloServer({
  schema,
});
```
What am I doing wrong? Do I have to put a `User` type into my own schema? Because the README suggests, that this gets added with this line:
```js
// Load all accounts related resolvers and type definitions into graphql-loader
initAccounts(options)
```
Thanks for your help!

**Comment by dbrrt** [comment]
@jschlieber 
I defined User type directly in my schema but you can use also, initAccounts for that;  in my case I'd rather the more explicit way, for project maintainability.

**Comment by NitroBAY** [comment]
I'm unsure to understand. [SchemaTypes (from auth)](https://github.com/orionsoft/meteor-apollo-accounts/blob/master/meteor-server/src/Auth.js) actually has defined `user: User`

**Comment by dbrrt** [comment]
@NitroBAY   Type User is defined by default with name property, but you can override this definition with your own properties (e.g. : Groups, Roles, Firstname ...).

**Comment by NitroBAY** [comment]
I'm new to GraphQL so please can you explain simply why the started code doesn't work (`Type "User" not found in document.`)

**Comment by NitroBAY** [comment]
if Type User is defined by default why do `initAccounts()` throws `Error: Type "User" not found in document.`

**Comment by dbrrt** [comment]
@NitroBAY , my bad, actually there's a reference to a non existing Type in "Auth.js", and you've to define it by yourself in your GraphQL schema; for the purpose of your application(s)/API.

Here's one possible definition for Type User  and as you can see, you can use as many "sub-structures" as you want, to describe the entity User you want.
I can help you with the implementation if something wasn't clear.

``` graphql
type User {
  _id: ID
  emails: [Email]
  profile: UserProfile
}
type Email {
  address: String
  verified: Boolean
}

type UserProfile {
  firstname: String
  lastname: String
  fullname: String
  groups: [UserGroup]
}

type UserGroup {
  group: String,
  role: String
}

```

**Comment by NitroBAY** [comment]
Okay I figured out that by myself. Thanks.

**Comment by csillag** [comment]
@NitroBAY 

> EDIT : PS : I'm not familiar with GraphQL, Meteor makes me come to the GraphQL land.

In that case, I suggest that you might want to consider to ...
..
... RUN FOR YOUR LIFE!

Currently, this area feels like a minefield, full off pre-alpha software (sometimes advertised as "production-ready"), and unfinished implementations... this is *not* where you want to be, unless your exact requirements make it impossible to avoid.

**Comment by NitroBAY** [comment]
I like challenges.

**Comment by visiOOn** [comment]
@dbrrt i am also new to graphql and apollo and i do not understand your answer. Where would i put that code

**Comment by dbrrt** [comment]
@visiOOn it correspond to the GraphQL schema that you load when you start your GraphQL/Apollo server : http://graphql.org/graphql-js/type/ 
You'll find a minimal boilerplate there : https://github.com/apollographql/apollo-tutorial-kit 
Schema is defined in : https://github.com/apollographql/apollo-tutorial-kit/blob/master/data/schema.js

**Comment by macrozone** [comment]
@nicolaslopezj this has been closed without providing any fix nor change in the README. Can you reopen this?

**Comment by acomito** [comment]
Latest apollo server doesn't really use makeExecutableSchema, so this could use some updating
