### ISSUE TITLE
Why are not all mutations included?

### ISSUE THREAD

**Issue by jsbranco** [orionsoft/meteor-apollo-accounts#46]
Hi, I just added this package into my Meteor App and I can see the basic Mutation added 
![screen shot 2017-04-12 at 5 03 13 pm](https://cloud.githubusercontent.com/assets/11029783/24949974/f8ed9a7a-1fa1-11e7-8af7-294223ad121a.png)

However, I don't see the mutations of loginwithFacebook added? I know there is a check "hasService" which looks are the packages to see if accounts-facebook is present, but is this required? The reason why I am asking is because while using Meteor 1.4.4 together with meteor-apollo-accounts and accounts-facebook package, I am getting  the following error:

>  Error: Already registered the facebook OAuth service
W20170412-16:56:55.966(8)? (STDERR)     at Object.OAuth.registerService (packages/oauth.js:65:11)
W20170412-16:56:55.966(8)? (STDERR)     at packages/facebook-oauth.js:49:7
W20170412-16:56:55.967(8)? (STDERR)     at packages/facebook-oauth.js:125:4
W20170412-16:56:55.967(8)? (STDERR)     at packages/facebook-oauth.js:137:3
W20170412-16:56:55.967(8)? (STDERR)     at /Users/juniobranco/IdeaProjects/sorteios_mreact/.meteor/local/build/programs/server/boot.js:303:34
W20170412-16:56:55.968(8)? (STDERR)     at Array.forEach (native)
W20170412-16:56:55.968(8)? (STDERR)     at Function._.each._.forEach (/Users/juniobranco/.meteor/packages/meteor-tool/.1.4.4_1.1re4zut++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170412-16:56:55.968(8)? (STDERR)     at /Users/juniobranco/IdeaProjects/sorteios_mreact/.meteor/local/build/programs/server/boot.js:128:5
W20170412-16:56:55.969(8)? (STDERR)     at /Users/juniobranco/IdeaProjects/sorteios_mreact/.meteor/local/build/programs/server/boot.js:352:5
W20170412-16:56:55.969(8)? (STDERR)     at Function.run (/Users/juniobranco/IdeaProjects/sorteios_mreact/.meteor/local/build/programs/server/profile.js:510:12)

**Comment by jsbranco** [comment]
After doing a meteor update it got resolved.

**Comment by nicolaslopezj** [comment]
We could make a new version where we configure the available oauth logins in code, not installing packages that are not needed

**Comment by jsbranco** [comment]
@nicolaslopezj  I think that is a sensible way since the current approach will check if accounts-facebook (or any other accounts-*) so that it can add the relevant mutations. 

As the PR I raised suggests, this ties meteor-apollo-accounts dependencies to accounts-* dependencies. which when changed can create some conflicts.

**Comment by jsbranco** [comment]
@nicolaslopezj  are there any on going discussions to make the changes so that is not dependent on packages?

**Comment by nicolaslopezj** [comment]
Fixed in 3.2.0
