### ISSUE TITLE
wrong package name in error-message

### ISSUE THREAD

**Issue by csillag** [orionsoft/meteor-apollo-accounts#48]
When checking the versions of the NPM dependencies, this packages [specifies](
https://github.com/orionsoft/meteor-apollo-accounts/blob/32d95f2f85805fdfc39c0436013e14c7560469c3/meteor-server/src/checkNpm.js#L5) a fake name, which will then show up the error messages on the console, making it hard to understand what's going on.

(It should say `nicolaslopezj:apollo-accounts`, instead of `orionsoft:stripe-graphql`.)

**Comment by nicolaslopezj** [comment]
Oh sorry
