### ISSUE TITLE
depends on obsolete version of graphql-loader

### ISSUE THREAD

**Issue by csillag** [orionsoft/meteor-apollo-accounts#49]
This package depends on `graphql-loader@1.0.x`, but the current stable version is 1.2.0.
The dependency should be updated.

**Comment by nicolaslopezj** [comment]
It's not the version ```1.0.2```?

https://www.npmjs.com/package/graphql-loader

**Comment by nicolaslopezj** [comment]
Sorry my bad, now its fixed
