### ISSUE TITLE
Breaks more complex GraphQL schemas

### ISSUE THREAD

**Issue by csillag** [orionsoft/meteor-apollo-accounts#50]
This package currently depends on [graphql-loader](https://github.com/orionsoft/graphql-loader), but that package has an issue (https://github.com/orionsoft/graphql-loader/issues/4) which makes that package unusable with some GraphQL schemas.

Because of this, trying to introduce apollo-accounts to our project is impossible right now.

**Comment by csillag** [comment]
I have a PR to fix this (and another) problem (see https://github.com/orionsoft/graphql-loader/pull/6); meanwhile I will just use my fork.

**Comment by nicolaslopezj** [comment]
Fixed now
